CREATE DATABASE IF NOT EXISTS Proyecto1_Fase1;

USE Proyecto1_Fase1;

CREATE TABLE IF NOT EXISTS cpu_info (
  id SERIAL PRIMARY KEY,
  usage_percentage NUMERIC(3, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS memory_info (
  id SERIAL PRIMARY KEY,
  total_memory BIGINT NOT NULL,
  free_memory BIGINT NOT NULL,
  used_memory BIGINT NOT NULL,
  memory_usage_percentage NUMERIC(3, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

